DROP TABLE IF EXISTS CLIENT;
CREATE TABLE CLIENT (
	CLIENT_KEY BIGINT AUTO_INCREMENT,
	CLIENT_NAME VARCHAR(255) NOT NULL,
	CLIENT_CIF VARCHAR(20),
	CLIENT_SUBNAME VARCHAR(255),
	CLIENT_ADDRESS VARCHAR(255),
	CLIENT_ZIPCODE CHAR(5),
	CLIENT_CITY VARCHAR(50),
	CLIENT_PROVINCE VARCHAR(50)
);

DROP TABLE IF EXISTS NOTE;
CREATE TABLE NOTE (
	NOTE_KEY BIGINT AUTO_INCREMENT,
	NOTE_NAME VARCHAR(50),
	NOTE_TEXT VARCHAR(255),
);

DROP TABLE IF EXISTS INVOICE;
CREATE TABLE INVOICE (
	INVOICE_KEY BIGINT AUTO_INCREMENT,
	CLIENT_KEY BIGINT,
	NOTE_KEY BIGINT,
	INVOICE_BASE DOUBLE,
	INVOICE_VAT DOUBLE,
	INVOICE_RENT DOUBLE,
	INVOICE_CONCEPT VARCHAR(255),
	INVOICE_DATE DATE,
	INVOICE_NUMBER INTEGER,
	INVOICE_QUOTE BOOLEAN,
	INVOICE_ISSUED BOOLEAN
);


ALTER TABLE INVOICE
	ADD FOREIGN KEY (CLIENT_KEY)
	REFERENCES CLIENT(CLIENT_KEY);
	
ALTER TABLE INVOICE
	ADD FOREIGN KEY (NOTE_KEY)
	REFERENCES NOTE(NOTE_KEY);